{
 "title": "K8s-dashboard-PODS",
 "description": "pods dashboard",
 "tags": [ "kubernetes, pods" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "NAMESPACE",
    "query": "query_result(sum(container_memory_working_set_bytes{namespace!=\"\"}) by (namespace))"
   },
   {
    "name": "pod",
    "label": "POD",
    "query": "query_result(sum(container_memory_working_set_bytes{namespace=\"$namespace\"}) by (pod_name))"
   }
  ]
 },
 "panels": [
  { "title": "CPU and Memory ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Namespace Memory Usage : $namespace",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(namespace) (container_memory_usage_bytes{namespace=\"$namespace\",container!=\"pod\",image!=\"\"})/1048576",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Core Usage vs Requested : $pod",
   "type": "graph",
   "description": "This graph attempts to show you CPU use of your application vs its requests",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\"}[1m])) by (container_name)",
     "legendFormat": "{{ container_name }}"
    },
    {
     "expr": "sum(container_spec_cpu_shares{namespace=~\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\"}) by (container_name) / 1000",
     "legendFormat": "{{ container_name }} (requested)"
    }
   ]
  },
  {
   "title": "Container Memory Stats",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (container)(container_memory_working_set_bytes{namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",image!=\"\"})/1048576",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(rate (container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod=\"$pod\",container!=\"POD\",container!=\"\"}[1m])) ",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "RAM Usage vs Requested : $pod",
   "type": "graph",
   "description": "This graph attempts to show you RAM use of your application vs its requests",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (avg_over_time (container_memory_working_set_bytes{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\"}[1m])) by (container_name)",
     "legendFormat": "{{ container_name }}"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{namespace=~\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\"}) by (container_name)",
     "legendFormat": "{{ container_name }} (requested)"
    }
   ]
  }
 ]
}