{
 "title": "Kubernetes Cluster (Prometheus)",
 "description": "Summary metrics about containers running on Kubernetes nodes.\r\n\r\nDashboard was taken from here.  This version does not reqiure you to\r\nsetup the Kubernetes-app plugin. (https://github.com/grafana/kubernetes-app)\r\n\r\nUse this Helm chart to launch Grafana into a Kubernetes cluster.  It will include this dashboard and many more dashboards to give you visibility into the Kubernetes Cluster. (https://github.com/sekka1/cloud-public/tree/master/kubernetes/pods/grafana-helm)",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, node)"
   },
   {
    "name": "namespace",
    "query": "query_result(sum(container_memory_working_set_bytes{namespace!=\"\"}) by (namespace))"
   },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Pod Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=~\"$node\"}) / sum(kube_node_status_allocatable_pods{node=~\".*\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"}) / sum(kube_node_status_allocatable_cpu_cores{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"}) / sum(kube_node_status_allocatable_memory_bytes{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (node_filesystem_size{nodename=~\"$node\"}) - sum (node_filesystem_free{nodename=~\"$node\"})) / sum (node_filesystem_size{nodename=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster Pod Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "pods" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_pods{node=~\"$node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_pods{node=~\"$node\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_info{node=~\"$node\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster CPU Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores{node=~\"$node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\"$node\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster Mem Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_memory_bytes{node=~\"$node\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster Disk Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size{nodename=~\"$node\"}) - sum(node_filesystem_free{nodename=~\"$node\"})",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(node_filesystem_size{nodename=~\"$node\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deployment Replicas - Up To Date",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\"}",
       "legendFormat": "{{ deployment }}"
      }
     ]
    },
    {
     "title": "Deployment Replicas",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Updated",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Unavailable",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Number Of Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_info{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Nodes Out of Disk",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\", node=~\"$node\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node\"})"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Pods Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Unknown\"})"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Containers Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 30 Minutes)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts{namespace=\"kube-system\"}[30m]))"
    }
   ]
  },
  {
   "title": "CPU Cores Requested by Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Memory Requested By Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 26 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", node=~\"$node\"})"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Jobs Succeeded",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_job_status_succeeded{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Jobs Succeeded",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_job_status_active{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Jobs Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"$namespace\"})"
    }
   ]
  }
 ]
}